USE [master]
GO

/****** Object:  Database [Powerfront]    Script Date: 08/09/2016 10:48:30 ******/
DROP DATABASE [Powerfront]
GO

/****** Object:  Database [Powerfront]    Script Date: 08/09/2016 10:48:30 ******/
CREATE DATABASE [Powerfront]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Powerfront', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Powerfront.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Powerfront_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Powerfront_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Powerfront] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Powerfront].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Powerfront] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Powerfront] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Powerfront] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Powerfront] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Powerfront] SET ARITHABORT OFF 
GO

ALTER DATABASE [Powerfront] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Powerfront] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Powerfront] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Powerfront] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Powerfront] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Powerfront] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Powerfront] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Powerfront] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Powerfront] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Powerfront] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Powerfront] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Powerfront] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Powerfront] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Powerfront] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Powerfront] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Powerfront] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Powerfront] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Powerfront] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Powerfront] SET RECOVERY FULL 
GO

ALTER DATABASE [Powerfront] SET  MULTI_USER 
GO

ALTER DATABASE [Powerfront] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Powerfront] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Powerfront] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Powerfront] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Powerfront] SET  READ_WRITE 
GO


