//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Powerfront.Backend.Impact.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiaryGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BeneficiaryGroup()
        {
            this.Impacts = new HashSet<Impact>();
        }
    
        public System.Guid BeneficiaryGroupId { get; set; }
        public string BeneficiaryGroupDescription { get; set; }
        public Nullable<System.Guid> ImpactId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Impact> Impacts { get; set; }
        public virtual Impact Impact { get; set; }
    }
}
